Check development leftovers

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -102,6 +102,27 @@ jobs:
         name: Check coding style
         run: php-cs-fixer check --diff --ansi --no-interaction -vvv --using-cache=no
 
+  check-development-leftovers:
+    name: Check Development Leftovers
+    runs-on: ubuntu-latest
+    steps:
+      -
+        name: Checkout
+        uses: actions/checkout@v4
+      -
+        name: Search for debugger or xdebug_break
+        run: |
+          echo "Scanning for 'debugger' or 'xdebug_break'..."
+          matches=$(grep -Enr --include=\*.{js,php,ts} '(^|[^a-zA-Z0-9_])(debugger|xdebug_break)\b' . || true)
+          if [[ -n "$matches" ]]; then
+            echo "Found the following matches:"
+            echo "$matches"
+            echo "::error::Development leftovers found in the codebase."
+            exit 1
+          else
+            echo "No development leftovers found."
+          fi
+
   check-install:
     name: Install on Concrete ${{ matrix.ccm-version }}
     runs-on: ubuntu-latest
@@ -109,6 +130,7 @@ jobs:
     needs:
       - check-php-syntax
       - check-php-coding-style
+      - check-development-leftovers
     strategy:
       matrix:
         ccm-version:
